version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: my_database
        MYSQL_USER: user
        MYSQL_PASSWORD: user_password
    ports:
        - "9990:3306"
    volumes:
      - mysql_data_temp_harsh:/var/lib/mysql

  redis:
    image: redis:7.2.0
    container_name: redis-container
    ports:
      - "9991:6379"
    volumes:
      - redis_data:/data

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true

# Mounts a volume to persist data.
volumes:
  mysql_data_temp_harsh:
  redis_data: